### ISSUE TITLE
Thank You

### ISSUE THREAD

**Issue by DMiradakis** [DevExpress-Examples/winforms-dashboard-viewer-tab-navigation-buttons-tab-animation#1]
DevExpress Team,

I just wanted to say **thank you** for this repository! Almost every time I have an interesting idea to do something to your dashboards, it's like you've already thought ahead.

The effort and ingenuity you put into your documentation and GitHub examples is GREATLY appreciated!

Thanks! 😄

**Comment by SergeyNakhankov** [comment]
Hi!

Compliments that we receive from our customers are the best reward for all of us. Please feel free to contact us if you have any questions. We are happy to help you at any time.
